[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "796ba6560042e710a9175d1c6a32041298d22542"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "523b09a8d6f6fe340cc59978c87c2b89ef732d7e1726020371dd403c7353e4a6"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.aarch64-linux-musl-cxx03.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bd9b2b4f5a3712e0cd62d92d1a61ab793068603"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "98a3551edb6bedcf4001fd482a7ad3bda96496b4bc84ef73ea70a93b14b3694d"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.aarch64-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c80f42868e4ae3cc9574d27ca6f5ab558f90fb02"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "1832a157a97fe90a3dc4f863632ac32fb6cdd46ba261b037fe04efa567718a02"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15519fb3a4f5d8a993cdbe599c3cbf1c0386715a"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "6753327b5458e3c118c66aefc4d0b313391baa532e08f457306a2e835f7a0a6b"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.i686-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db1951ded78e5a4014958f0cbdb987d17d99697e"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "9977ee38008e5b1db2734a634de840a2b103c0ffaf48dfb27d96231200105103"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6af0b652aa12c1f69eafc0f46ab3f2d064d32f4"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "49e8988b1736f1870602203d81abae001b311fc9a81233cbb4aef6ba40a7f6ed"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c956914b1cd4f0f3dcf69ee72d44dbf41400dcac"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "2c47a27b7a4545b0c157f97eea0ff3ed05df9e7dbaed0ae60d701494aebc6cf2"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.i686-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05b4bcf6b87541795cebdcb2ec42f2617af03590"
os = "macos"

    [[Elemental.download]]
    sha256 = "ca6f6989a6c37ddbf3c6be4fc5c4f9654b47cfcaf39f42661ac2bda479842fda"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-apple-darwin14-cxx11.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "194129fe58e2720cd471b79ffd70e443409990dc"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "e2a23f94314738f1e61e65f88572f919a8ad591c9b4140a81f3faec4cb7ac709"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.i686-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d35741c36b8d902f14d9eba0ed32fd61bebbedef"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "bfa7de3e4977974dba9e41681054e3c56c06870dc1ee65365a33a7aec678a198"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdec30ba2ffca22e8ba9d510a6e2c895947a6c73"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "74adc4b65b043db93ac29d58122f22b13a1326857356b0ac38334f6d9ffe7a4c"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac9912a98d018e447c76c27ce44a5b54f8c9e98e"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "31cca9f74bc7acb4b1cd14ec29194a7711f667583e58dbe182976e5329a75be6"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.aarch64-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e2733f14fbbe7eebcd66141aa4164ac08b77142"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "690013517c1ffe837e9597cdc888b4b4b41489135fa6722126c6c0afc3f1dd58"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-linux-musl-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d6d454d841e2edfebde7163c1b724d9d335c5d"
os = "macos"

    [[Elemental.download]]
    sha256 = "db9f158fe9d49efbd53ef3fe8c675b645262fd6cdd7e700745713193025390ea"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-apple-darwin14-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69aa7c4b383edb80774b9a28520988be59018de3"
os = "freebsd"

    [[Elemental.download]]
    sha256 = "925e510e16fdbc531909f2052950ffabe45ca0fe7160673990d49f645d93569d"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Elemental]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcbdf09d2cfd17fc070a17fe6326b388c8d3ba08"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "9bd47ae839cf0515e9e888967a84a7d98a43e0ac692c655ee80ed33dce928083"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb780edfc844e911bf347b13a847ae9b60697947"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "ae84c6f4aacf30f21cbc26db0de08a62605f9d993cdd296d9e8fac61f471d892"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50fc949a48143667376be70f0f5814b20053f23e"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "72a1553c51e5e316b162f42403896ec364e45d6ea42bcd1b8b9d87f7d2a59ea9"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e12522b6f84d3f51e17bd5300afa373b4a6fe2a3"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "285555e96f6b7fa46138553549f040a720cceb1be97e9466ede3e71c37d21a5c"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.aarch64-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c434e7fb9dc89e0f2a72a8d3ad5c93e2ba3303a7"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "2cf2f28af24c783c0b6c0d43eae20f874e9144338c797ede7d1d5d4b37852c32"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07878f0cc03bfba5fbfe9c4ea717cbb459ba2530"
os = "freebsd"

    [[Elemental.download]]
    sha256 = "e915c04c7eff8aba6d9b09ebd5dc347eb448c4e0a44424b5e5c0be7edf2a81a7"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef86ffd5ce5a7c93486203001c64cd747971b15c"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "a42bd0c8eb7d216d5748ca758fb836fd2adbacb846c7925e967365a3e789c96b"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v0.87.7+1/Elemental.v0.87.7.i686-linux-musl-cxx03.tar.gz"
