[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d017ca9332d2034aadb4ff03428b2e35698da90"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "4f58d8bd4639a4d7b1d86de2cd5b83545a189669631e6c65fe86bb26df973e54"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.aarch64-linux-musl-cxx03.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d88f39635d0e8cc9ffe166fd8207fe30a128b2c"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "240b4bb929c3c9d3c723d6fd3d37b25aef103295f118f82d1d36d52c7647401a"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.aarch64-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a48cffecdaa86da4e45ab5f86f3daf96e055562f"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "af47c75cf8a88b35f6e6ce57f4346915b0dd622d7cb919f35dbfca17c703bae1"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "557bdccafcc36f3cdbca158b5db0b0745b5ecbb2"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "05bd9f8e3449784ac01f19918246db4856efcfcd4a79d2be266830ab8fa7ace6"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.i686-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed1d949e168499d1c155c38bb717c8e9e604502e"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "86e747323a792014bcc3ebfc763792d0dd7420c1ce000514a816a611091c747f"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-linux-musl-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58e1bb90195841f4d4d313d163c794c1ad9a2014"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "07fd0ec37ae7dae84eaa80941ff590104760e75eb2a31dc4c1392dc5638a9f1b"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d850cf73f5a35a8c951da04a9e4a7f1955185ca"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "d79c1729d394ad25b353b38b8af43b895176f0cf400e0f66fc5537ee2bf73774"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.i686-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45e2d4767cec0067609093fb0ec96fe5040092c1"
os = "macos"

    [[Elemental.download]]
    sha256 = "7f1b6a1187d6606bf38cfd2637271ce2f6effb25cb5c507f51db6c4891ab6ef8"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f9777abef642505ef8f13b3759d4999921a6771"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "fa83207f9c134ebdbd7879ba4eaf7826c18371c246ad7018cb9c659bfe4daff0"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.i686-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93ffbf507bc77719f55c02ac9931e83aef9f67e3"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "9ede8e7b653372540cac4d29260bcaf78762313a78fcf9e61f14b0c6d0bf15e2"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19f8bc69cdb6eda3a918cf39ec8e927f61a1153a"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "8f3dae0783b59e02333c0e3fa89027461d50d62cf2b2ea34d0a21313a7e6baf6"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a2ce19c4972d2adcf952fd7c84ae4472429c8f1"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "ad50d1c4949938aaed80ffe5607fd0bd082bb17d99e28af0f7fc444aebe08d8d"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fd468fc1ed027eb2c43e0ffe2b572d8929a0603"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "5e282543e1a9e1030431adfc0de433f6cb523127b3040aee9d0f8862f5aef3e4"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-linux-musl-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66c4fb8932a6f88b4234092f73d2dd2ed07d7f33"
os = "macos"

    [[Elemental.download]]
    sha256 = "36e12dd43c35d00888c271f32d6b3fa7034efcec2872874e0d19519cd9acdea3"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "496831973d13be2afb783d7ddf23472867ec23d6"
os = "freebsd"

    [[Elemental.download]]
    sha256 = "ea5c0ac7c8f2ec7d503075b8b1b0ba5d25ae24efe7c460e606e9d4b803e940e8"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Elemental]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d647f18e8809e8588287bfb408b7a47680927b0"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "98cb6f03d8a9696f185a80213f2fc619474d5864eb370a7f6228884911fdf5ae"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64e93f7c68e8d2b11a0bf28e52ee78c1882da016"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "0a7057316b24e0415c5fb78a2d28c072e90c56cad73d5a73dab166bfabedf470"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57d183a5182d5c061d36383bb49f032a29d8369d"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "3bc65b6f9660034d4d818cde85446f9f03f8d45236420ad41689e751ec683ca8"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Elemental]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aed9fb194033a14ce6c9a0d6939f24168a8b309"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "a375432561040b36fb34e9708b81acdb04fae08d6e86a4997a27b566e3538378"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Elemental]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e39d5928d584690c2ec269d56024ddd55bcfda28"
libc = "glibc"
os = "linux"

    [[Elemental.download]]
    sha256 = "e905ce788d4493ba86fcfe4737dc13f60bc2195b791236268e50895bad4a1c61"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Elemental]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fd82389749a42c496423b91030ae422dd0532d0"
os = "freebsd"

    [[Elemental.download]]
    sha256 = "82215d3add31d8ca16654e3e0e27516433d2bef707d8ffa53cbeb3fba4a21218"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Elemental]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ece9181acfe0bf612f4a69685b18c212e04a121"
libc = "musl"
os = "linux"

    [[Elemental.download]]
    sha256 = "36c4b2d99173a437899e9d9f995f9b1275275f9deb9d5fd1bfbbddc0f9c0e56c"
    url = "https://github.com/JuliaBinaryWrappers/Elemental_jll.jl/releases/download/Elemental-v1.3.3+0/Elemental.v1.3.3.i686-linux-musl-cxx03.tar.gz"
