# Autogenerated wrapper script for Elemental_jll for armv7l-linux-gnueabihf-libgfortran4-cxx11-mpi+mpich
export libEl, libElSuiteSparse

using METIS_jll
using OpenBLAS_jll
using MPICH_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("Elemental")
JLLWrappers.@declare_library_product(libEl, "libEl.so.0")
JLLWrappers.@declare_library_product(libElSuiteSparse, "libElSuiteSparse.so.0")
function __init__()
    JLLWrappers.@generate_init_header(METIS_jll, OpenBLAS_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libEl,
        "lib/libEl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libElSuiteSparse,
        "lib/libElSuiteSparse.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
